package com.royalenfield.diagcan.iso14229UDS.TemplateCompilerEngine;

public enum UdsParseExceptionType {
    MISSING_SID_ATTRIBUTE,
    INVALID_SID_FORMAT,
    INVALID_SID_ATTRIBUTE_FORMAT,
    MISSING_ELEMENT,
    MISSING_REQUEST_TYPE,
    INVALID_SESSION_TYPE,
    ERROR_PARSING_SUPPRESS_POSITIVE_RESPONSE,
    INVALID_SUBFUNCTION_ID,
    MISSING_SUBFUNCTION_ID,
    MISSING_SESSION_NAME,
    ERROR_PARSING_PARAMETER_RECORD,
    MISSING_SECURITY_LEVEL,
    INVALID_SECURITY_LEVEL,
    INVALID_BLOCK_SEQUENCE_COUNTER,
    MISSING_BLOCK_SEQUENCE_COUNTER,
    MISSING_SECURITY_REQUESTING,
    ERROR_PARSING_OPTIONAL_BYTES_USED,
    MISSING_OPTIONAL_BYTES_ELEMENT,
    INVALID_OPTIONAL_BYTES_FORMAT,
    INVALID_ROUTINE_IDENTIFIER,
    INVALID_OPTIONAL_BYTES_BUFFER_LENGTH,
    INVALID_OPTIONAL_BYTES,
    INVALID_HEX_SHORT

}
